export const RECIEVE_PROFILE_ERROR = 'RECIEVE_PROFILE_ERROR';
export const RECIEVE_COURSES_OPTIONS = 'RECIEVE_COURSES_OPTIONS';
export const RECEIVE_LOCATION_OPTIONS = 'RECEIVE_LOCATION_OPTIONS';
export const RECEIVE_LANGUAGE_OPTIONS = 'RECEIVE_LANGUAGE_OPTIONS';
export const RECIEVE_MAJOR_OPTIONS = 'RECIEVE_MAJOR_OPTIONS';
