export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const RECIEVE_PROFILE = "RECIEVE_PROFILE";
export const OPEN_NEWPROFILE_FORM = "OPEN_NEWPROFILE_FORM";
export const RECIEVE_PROFILE_PIC = "RECIEVE_PROFILE_PIC";
export const RECEIVE_COURSES = "RECIEVE_COURSES";
export const RECEIVE_PROFILE_WITH_COURSE = 'RECEIVE_PROFILE_WITH_COURSE';
