export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const RECIEVE_PROFILE = "RECIEVE_PROFILE";
export const OPEN_NEWPROFILE_FORM = "OPEN_NEWPROFILE_FORM";
export const RECIEVE_PROFILE_PIC = "RECIEVE_PROFILE_PIC";
export const RECIEVE_COURSES_OPTIONS = "RECIEVE_COURSES_OPTIONS";
export const RECEIVE_PROFILE_WITH_COURSE = 'RECEIVE_PROFILE_WITH_COURSE';
export const OPEN_UPDATEPROFILE_FORM = 'OPEN_UPDATEPROFILE_FORM';
export const CLOSE_UPDATEPROFILE_FORM = 'CLOSE_UPDATEPROFILE_FORM';